In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
#dropping column id and unnamed:32
df = df.drop(columns=['id', 'Unnamed: 32'], errors='ignore')
print(df.shape)

(569, 31)

Test Train split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Now, scaling the data

In [ ]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [ ]:
X_train

array([[-0.69147447,  1.18995498, -0.70472231, ..., -0.98411395,
         0.5476924 , -0.90465127],
       [-0.24587107,  0.31606891, -0.21152066, ...,  0.08076766,
        -0.53746266, -0.12380818],
       [-1.24818936, -1.45500687, -1.1290856 , ..., -0.0806011 ,
        -0.08332287,  2.86295763],
       ...,
       [-0.96635968,  1.36007147, -0.96580437, ..., -0.78301193,
         0.81061543, -0.13856168],
       [-0.07225936, -0.34342378, -0.121695  , ..., -0.80082339,
        -0.87687239, -0.75766261],
       [-1.47909294, -0.9073716 , -1.43885821, ..., -0.99218239,
        -0.74302066, -0.52980287]])

In [ ]:
X_test

array([[ 2.6910604 ,  1.69797409,  2.84926779, ...,  2.44344994,
         0.47439265,  0.19749045],
       [ 1.23272202,  0.13896133,  1.19966568, ...,  1.22405013,
         0.2592738 , -0.01780149],
       [-0.62202978, -0.10339641, -0.65099481, ..., -0.66472558,
        -0.5820799 , -0.22271132],
       ...,
       [-0.31531575, -0.80716599, -0.30554378, ..., -0.17650895,
         1.03370164, -0.15440804],
       [-1.22909207, -0.86542507, -1.23905908, ..., -0.93174522,
        -0.09447718, -0.12326175],
       [-0.39633455, -0.52053136, -0.43650456, ..., -0.21746008,
         0.5891227 , -0.58499192]])

Label Encoding

In [ ]:
y_train

305    B
466    B
505    B
489    M
495    B
      ..
312    B
511    B
248    B
149    B
358    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
y_test

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0])

Transform numpy to tensor

In [ ]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

Defining the model

In [58]:
class MySimpleNN:
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
   epsilon=1e-7
   loss=-(y_train_tensor*torch.log(y_pred+epsilon)+(1-y_train_tensor)*torch.log(1-y_pred+epsilon)).mean()
   return loss

Important Parameter

In [63]:
learning_rate=0.1
epochs=1

Training pipeline

In [64]:
#create model
model=MySimpleNN(X_train_tensor) #object of class we created

#define loop
for epoch in range(epochs):
#forward pass
 y_pred = model.forward(X_train_tensor)
#loss calculate
 loss=model.loss_function(y_pred,y_train_tensor)
 print(model.weights)

#backward pass

print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

tensor([[0.7408],
        [0.5759],
        [0.1344],
        [0.7029],
        [0.5378],
        [0.6959],
        [0.2662],
        [0.2210],
        [0.4909],
        [0.4047],
        [0.7105],
        [0.9471],
        [0.7277],
        [0.1260],
        [0.5797],
        [0.4816],
        [0.4628],
        [0.0496],
        [0.4952],
        [0.9468],
        [0.7827],
        [0.3300],
        [0.8800],
        [0.6550],
        [0.0468],
        [0.0963],
        [0.0692],
        [0.8747],
        [0.3410],
        [0.2254]], dtype=torch.float64, requires_grad=True)
Epoch: 1, Loss: 3.417197339601386