In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
#dropping column id and unnamed:32
df = df.drop(columns=['id', 'Unnamed: 32'], errors='ignore')
print(df.shape)

(569, 31)

Test Train split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Now, scaling the data

In [ ]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [ ]:
X_train

array([[ 0.16441414,  1.08354344,  0.20379134, ...,  0.68209856,
         0.64484544,  0.27772662],
       [-1.45808423, -0.48265051, -1.38068773, ...,  0.88792595,
         2.0974231 ,  1.8397454 ],
       [ 0.07695552,  1.3323337 ,  0.13854085, ...,  0.06310296,
         0.4302419 ,  1.00344088],
       ...,
       [ 1.07003399,  0.30637004,  1.04096754, ...,  1.22693577,
         0.226849  ,  0.05324488],
       [-0.26159396, -1.09159429, -0.31575036, ..., -0.24563813,
        -1.42752006, -1.21056531],
       [ 1.51014831,  2.22797865,  1.68936872, ...,  1.17699236,
        -0.16071858,  0.90440482]])

In [ ]:
X_test

array([[ 0.2180178 ,  0.09312125,  0.12581905, ..., -0.88975678,
        -0.43617984, -1.27713955],
       [-0.14310164, -0.78119882, -0.18853241, ..., -0.70315004,
         0.64804847, -0.38801579],
       [-0.27852143,  2.05974904, -0.31000503, ..., -0.55619533,
        -0.71324261, -1.08016783],
       ...,
       [-1.57996204, -0.18173276, -1.57356656, ..., -1.76058825,
         0.35817355, -0.15968265],
       [-0.66503208, -0.1011721 , -0.69453155, ..., -0.71434947,
        -0.61394844, -0.22735729],
       [-0.74966945, -1.16741609, -0.72982427, ..., -0.71359275,
        -0.94386134, -0.14977904]])

Label Encoding

In [ ]:
y_train

65     M
68     B
541    B
22     M
315    B
      ..
19     B
392    M
408    M
92     B
256    M
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1])

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0])

Transform numpy to tensor

In [ ]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float()
y_test_tensor=torch.from_numpy(y_test).float()

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
#using the dataset and dataloader class for training in batches
from torch.utils.data import Dataset,DataLoader
class CustomDataset(Dataset):
 def __init__(self,features,labels):
  self.features=features
  self.labels=labels
 def __len__(self):
  return len(self.features)
 def __getitem__(self,idx):
  return self.features[idx],self.labels[idx]

In [ ]:
#Creating two objects for training and testing dataset
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
#creating batches for both training and testing dataset
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

Defining the model

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
     out=self.linear(features)
     out=self.sigmoid(out)
     return out

Important Parameter

In [ ]:
learning_rate=0.1
epochs=25

Training pipeline

In [ ]:
#create model
model=MySimpleNN(X_train_tensor.shape[1]) #object of class we created

#define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

#define loss_function
loss_function=nn.BCELoss()


#training the model

#define loop
for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:
#forward pass
   y_pred = model(batch_features)
#loss calculate
   loss=loss_function(y_pred,batch_labels.view(-1,1))


#zero grad
   optimizer.zero_grad()

#backward pass
   loss.backward()

#parameters update
   optimizer.step()


  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.26075872778892517
Epoch: 2, Loss: 0.13954012095928192
Epoch: 3, Loss: 0.212637260556221
Epoch: 4, Loss: 0.21271535754203796
Epoch: 5, Loss: 0.2132812887430191
Epoch: 6, Loss: 0.15102173388004303
Epoch: 7, Loss: 0.0887230709195137
Epoch: 8, Loss: 0.019964711740612984
Epoch: 9, Loss: 0.09724472463130951
Epoch: 10, Loss: 0.03034253977239132
Epoch: 11, Loss: 0.009590069763362408
Epoch: 12, Loss: 0.17385077476501465
Epoch: 13, Loss: 0.08974761515855789
Epoch: 14, Loss: 0.16045978665351868
Epoch: 15, Loss: 0.006169520318508148
Epoch: 16, Loss: 0.014663116075098515
Epoch: 17, Loss: 0.009475432336330414
Epoch: 18, Loss: 0.019105521962046623
Epoch: 19, Loss: 0.03668734431266785
Epoch: 20, Loss: 0.013497681356966496
Epoch: 21, Loss: 0.007659215945750475
Epoch: 22, Loss: 0.02196447178721428
Epoch: 23, Loss: 0.0823744684457779
Epoch: 24, Loss: 0.05983154848217964
Epoch: 25, Loss: 0.0740254670381546

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.4729,  0.6197,  0.6564,  0.5678,  0.1512,  0.1936,  0.4100,  0.4803,
          0.1096, -0.1808,  0.5537,  0.2176,  0.4115,  0.4082,  0.0808, -0.3302,
         -0.0970,  0.0916, -0.1178, -0.4460,  0.7895,  0.5737,  0.6395,  0.6579,
          0.4730,  0.2373,  0.4350,  0.7276,  0.4132,  0.0989]],
       requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.2487], requires_grad=True)

Model Evaluation

In [ ]:
model.eval()  #sets the model in evaluation mode
accuracy_list=[]
#model evaluation
with torch.no_grad():   #evaluation mai backpropagation thodi kr rhe so off kro gradient
 for batch_features,batch_labels in test_loader:
  y_pred = model.forward(batch_features)
 # but hmare y_test_tensor is in form of label 0 & 1, so need to convert it into 0 and 1
  y_pred = (y_pred > 0.5).float()
  print(y_pred)
  #calulate batch accuracy
  batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
  accuracy_list.append(batch_accuracy)
  print(batch_accuracy)

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.]])
1.0
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.]])
0.9375
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.]])
0.96875
tensor([[1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.]])
0.9444444179534912

In [ ]:
sum_accuracy=sum(accuracy_list)
len_accuracy=len(accuracy_list);
overall_accuracy=sum_accuracy/len_accuracy
print(overall_accuracy)

0.9626736044883728